# Generated by Django 5.2.1 on 2025-05-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='Titulo', max_length=100)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=255, null=True)),
                ('categoria', models.CharField(blank=True, db_column='Categoria', max_length=50, null=True)),
                ('prioridade', models.CharField(blank=True, db_column='Prioridade', max_length=20, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=20, null=True)),
                ('data_abertura', models.DateField(db_column='Data_Abertura')),
                ('data_conclusao', models.DateField(blank=True, db_column='Data_Conclusao', null=True)),
            ],
            options={
                'db_table': 'Chamado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteAbre',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Cliente_Abre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('conteudo', models.CharField(db_column='Conteudo', max_length=255)),
            ],
            options={
                'db_table': 'Mensagem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='Tipo', max_length=50)),
            ],
            options={
                'db_table': 'Notificacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TecnicoAtende',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Tecnico_Atende',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=100)),
                ('email', models.CharField(db_column='Email', max_length=100, unique=True)),
                ('senha', models.CharField(db_column='Senha', max_length=100)),
                ('tipo_perfil', models.CharField(db_column='Tipo_Perfil', max_length=50)),
            ],
            options={
                'db_table': 'Usuario',
                'managed': False,
            },
        ),
    ]
