# Generated by Django 5.2.1 on 2025-05-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('prioridade', models.CharField(blank=True, db_column='Prioridade', max_length=100, null=True)),
                ('data_conclusao', models.DateField(blank=True, db_column='Data_Conclusao', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=100, null=True)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=100, null=True)),
                ('data_abertura', models.DateField(blank=True, db_column='Data_Abertura', null=True)),
                ('titulo', models.CharField(blank=True, db_column='Titulo', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Chamado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteAbre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Cliente_abre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('conteudo', models.CharField(blank=True, db_column='Conteudo', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Mensagem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Notificacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TecnicoAtende',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'tecnico_atende',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('senha', models.CharField(blank=True, db_column='Senha', max_length=100, null=True)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=100, null=True)),
                ('tipo_perfil', models.CharField(blank=True, db_column='Tipo_Perfil', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Usuario',
                'managed': False,
            },
        ),
    ]
